name: Build Pull Request

on:
  pull_request:

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    environment: goreleaser
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu
      - name: Build coinset-inspect staticlib
        run: |
          cargo build --release -p coinset-ffi --target x86_64-unknown-linux-gnu
          mkdir -p cgo-lib/x86_64-unknown-linux-gnu
          cp "target/x86_64-unknown-linux-gnu/release/libcoinset.a" cgo-lib/x86_64-unknown-linux-gnu/
      - name: Run GoReleaser (Build)
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: ~> v1
          args: build --clean --skip=validate -f .goreleaser.linux.yaml
        env:
          CGO_LDFLAGS: -L${{ github.workspace }}/cgo-lib/x86_64-unknown-linux-gnu
